### ISSUE TITLE
(Presentation) Nice Work!

### ISSUE THREAD

**Issue by CharlesDLandau** [dillec13/intro-data-capstone-musclehub#4]
Your presentation looks clean, covers all the bases, and does a good job of showing how data moves through your analysis from ingestion to recommendation. Your text is usually concise and in large formats: this is important for good presentations because too much text can make your material unreadable. While it can sometimes be nice to use tabular data, it's often redundant to your charts so in the future consider omitting it by default.

**Comment by dillec13** [comment]
Thanks. Guilty there; I’ve been accustomed to presenting to folks who only like to see the tabular data. Old habits die hard.
